### ISSUE TITLE
Man, this thing is crazy

### ISSUE THREAD

**Issue by jmcdo29** [JochCool/organised-javascript#2]
Not really an issue as this definitely won't be used in production, but just wanted to let you see how much this seriously screws up a webpacked JS file. I decided to run this against my NestJS applicaiton after using webpack to compile it (thanks to an Nx monorepo) and man, did this mess it up good. From 3516 lines to 11111 lines. It also doesn't run :laughing: 

https://gist.github.com/jmcdo29/3b1c0577071cbcb139b8f2babbe3d723

**Comment by JochCool** [comment]
Hi, thanks for sharing your result! That looks crazy. I've been looking at the errors and I think one bug causes all of them: #3. I'm not entirely sure how to fix it though, because just like #1 the problem is that the next token appears on a new line.
